---
apiVersion: v1
kind: Secret
metadata:
  name: questcode
  namespace: prod
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovLzE5Mi4xNjguMTg5LjQ3OjMwMDIxL3F1ZXN0Y29kZQ==
  SECRET_OR_KEY: cm9vdA==
  GITHUB_CLIENT_SECRET: YmVkNWE3NmI5ZjcyODI5ZjYyYmRhMmRiNmIyM2VmYTA1MzdkNjBlOA==
---
apiVersion: v1
kind: Secret
metadata:
  name: questcode
  namespace: staging
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovLzE5Mi4xNjguMTg5LjQ3OjMwMDIxL3F1ZXN0Y29kZQ==
  SECRET_OR_KEY: cm9vdA==
  GITHUB_CLIENT_SECRET: YmVkNWE3NmI5ZjcyODI5ZjYyYmRhMmRiNmIyM2VmYTA1MzdkNjBlOA==
---